namespace SpriteKind {
    export const trophy = SpriteKind.create()
}
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile1`, function (sprite, location) {
    game.over(false, effects.dissolve)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile`, function (sprite, location) {
    game.over(true, effects.confetti)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile4`, function (sprite, location) {
    game.over(false, effects.dissolve)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile3`, function (sprite, location) {
    game.over(false, effects.dissolve)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Projectile, function (sprite, otherSprite) {
    Bo.destroy()
    info.changeLifeBy(-1)
    scene.cameraShake(4, 500)
    game.over(false, effects.slash)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile2`, function (sprite, location) {
    game.over(false, effects.dissolve)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.trophy, function (sprite, otherSprite) {
    info.changeScoreBy(7)
    otherSprite.destroy()
})
let LT: Sprite = null
let Superbowl_Trophy: Sprite = null
let Bo: Sprite = null
scene.setBackgroundColor(7)
Bo = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . f f f f f b . . . 
    . . . . . . f f f f b f f b . . 
    . . . . . b f f f f f f f b . . 
    . . . . . b f f f f f f f b . . 
    . . . . . b f f f f f b 1 1 c c 
    . . . . . b b f f b 1 1 1 1 b c 
    . . . b b b f b f f b 1 1 1 d c 
    . . b b f f d f d f c d 4 4 c c 
    . . b b f f d f d d 4 1 1 4 c . 
    . . b 1 1 d d d d d 4 4 4 4 c . 
    . . . f f f f f d d 4 4 4 b c . 
    . . . . f f f f d d c c c c . . 
    . . . . . f f f f f c c c . . . 
    . . . . b b b f f . . . . . . . 
    . . . . b b b b f f . . . . . . 
    `, SpriteKind.Player)
controller.moveSprite(Bo, 100, 100)
tiles.setCurrentTilemap(tilemap`level1`)
scene.cameraFollowSprite(Bo)
info.setLife(1)
for (let value of tiles.getTilesByType(assets.tile`myTile7`)) {
    Superbowl_Trophy = sprites.create(img`
        . . . . . . c c c . . . . . . . 
        . . . . c c b b b c . . . . . . 
        . . . c c b b c b c . . . . . . 
        . . . c b b c b b c . . . . . . 
        . . c b b c b b c . . . . . . . 
        . . c b c b b b c . . . . . . . 
        . . c b b b b c . . . . . . . . 
        . . . c c c b c . . . . . . . . 
        . . . . . c b c . . . . . . . . 
        . . . . . c b c . . . . . . . . 
        . . . . . c b c . . . . . . . . 
        . . . . c b b b c . . . . . . . 
        . . . c b b b b b c . . . . . . 
        . . . . c b b b c . . . . . . . 
        . . . . . c b c . . . . . . . . 
        . . . . . . c . . . . . . . . . 
        `, SpriteKind.trophy)
    animation.runImageAnimation(
    Superbowl_Trophy,
    [img`
        .......ccc......
        .....ccbbbc.....
        ....ccbbcbc.....
        ....cbbcbbc.....
        ...cbbcbbc......
        ...cbcbbbc......
        ...cbbbbc.......
        ....cccbc.......
        ......cbc.......
        ......cbc.......
        ......cbc.......
        .....cbbbc......
        ....cbbbbbc.....
        .....cbbbc......
        ......cbc.......
        .......c........
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        `,img`
        ................
        .......ccc......
        .....ccbbbc.....
        ....ccbbcbc.....
        ....cbbcbbc.....
        ...cbbcbbc......
        ...cbcbbbc......
        ...cbbbbc.......
        ....cccbc.......
        ......cbc.......
        ......cbc.......
        ......cbc.......
        .....cbbbc......
        ....cbbbbbc.....
        .....cbbbc......
        ......cbc.......
        .......c........
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        `,img`
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        `],
    100,
    true
    )
    tiles.placeOnTile(Superbowl_Trophy, value)
    tiles.setTileAt(value, assets.tile`transparency16`)
}
for (let value of tiles.getTilesByType(assets.tile`myTile9`)) {
    LT = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . 6 8 8 8 8 8 . . . . . . . 
        . . 6 8 8 2 8 8 8 8 . . . . . . 
        . . 6 8 8 8 8 8 8 8 6 . . . . . 
        . . 6 8 8 8 8 8 8 8 6 . . . . . 
        6 6 1 1 2 8 8 8 8 8 6 . . . . . 
        6 2 1 1 1 1 2 8 8 6 6 . . . . . 
        6 d 1 1 1 2 8 8 2 8 6 6 6 . . . 
        6 6 2 2 d c 8 d 8 d 2 2 6 6 . . 
        . 6 8 8 8 2 d d 8 d 2 2 6 6 . . 
        . 6 2 8 8 2 d d d d d 1 1 6 . . 
        . 6 8 2 2 2 d d 8 8 8 8 8 . . . 
        . . 6 6 6 6 d d 8 8 8 8 . . . . 
        . . . 6 6 6 8 8 8 8 8 . . . . . 
        . . . . . . . 8 8 2 2 2 . . . . 
        . . . . . . 8 8 2 2 2 2 . . . . 
        `, SpriteKind.Projectile)
    tiles.placeOnTile(LT, value)
    LT.follow(Bo, 50)
}
game.onUpdate(function () {
    Bo.setImage(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . f f f f f b . . . 
        . . . . . . f f f f b f f b . . 
        . . . . . b f f f f f f f b . . 
        . . . . . b f f f f f f f b . . 
        . . . . . b f f f f f b 1 1 c c 
        . . . . . b b f f b 1 1 1 1 b c 
        . . . b b b f b f f b 1 1 1 d c 
        . . b b f f d f d f c d 4 4 c c 
        . . b b f f d f d d 4 1 1 4 c . 
        . . b 1 1 d d d d d 4 4 4 4 c . 
        . . . f f f f f d d 4 4 4 b c . 
        . . . . f f f f d d c c c c . . 
        . . . . . f f f f f c c c . . . 
        . . . . b b b f f . . . . . . . 
        . . . . b b b b f f . . . . . . 
        `)
    if (Bo.vx < 0) {
        Bo.image.flipX()
    }
})
game.onUpdate(function () {
    LT.setImage(img`
        . . . . . . . . . . . . . . . . 
        . . . 6 8 8 8 8 8 . . . . . . . 
        . . 6 8 8 2 8 8 8 8 . . . . . . 
        . . 6 8 8 8 8 8 8 8 6 . . . . . 
        . . 6 8 8 8 8 8 8 8 6 . . . . . 
        6 6 1 1 2 8 8 8 8 8 6 . . . . . 
        6 2 1 1 1 1 2 8 8 6 6 . . . . . 
        6 d 1 1 1 2 8 8 2 8 6 6 6 . . . 
        6 6 2 2 d c 8 d 8 d 2 2 6 6 . . 
        . 6 8 8 8 2 d d 8 d 2 2 6 6 . . 
        . 6 2 8 8 2 d d d d d 1 1 6 . . 
        . 6 8 2 2 2 d d 8 8 8 8 8 . . . 
        . . 6 6 6 6 d d 8 8 8 8 . . . . 
        . . . 6 6 6 8 8 8 8 8 . . . . . 
        . . . . . . . 8 8 2 2 2 . . . . 
        . . . . . . 8 8 2 2 2 2 . . . . 
        `)
    if (LT.x < 0) {
        LT.image.flipX()
    }
})
